///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CURARanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CURARanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("39f8fcac-d4a6-4389-93bc-5e8ff574dd6a")]
    public partial class CURARanorexRepository : RepoGenBaseFolder
    {
        static CURARanorexRepository instance = new CURARanorexRepository();
        CURARanorexRepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder _curahealthcareservicegooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the CURARanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("39f8fcac-d4a6-4389-93bc-5e8ff574dd6a")]
        public static CURARanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CURARanorexRepository() 
            : base("CURARanorexRepository", "/", null, 0, false, "39f8fcac-d4a6-4389-93bc-5e8ff574dd6a", ".\\RepositoryImages\\CURARanorexRepository39f8fcac.rximgres")
        {
            _curahealthcareservicegooglechrome = new CURARanorexRepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("39f8fcac-d4a6-4389-93bc-5e8ff574dd6a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CURAHealthcareServiceGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("84e8fc4d-1d0e-4511-87b0-68090e09674d")]
        public virtual CURARanorexRepositoryFolders.CURAHealthcareServiceGoogleChromeAppFolder CURAHealthcareServiceGoogleChrome
        {
            get { return _curahealthcareservicegooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class CURARanorexRepositoryFolders
    {
        /// <summary>
        /// The CURAHealthcareServiceGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("84e8fc4d-1d0e-4511-87b0-68090e09674d")]
        public partial class CURAHealthcareServiceGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element241933216Info;

            /// <summary>
            /// Creates a new CURAHealthcareServiceGoogleChrome  folder.
            /// </summary>
            public CURAHealthcareServiceGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CURAHealthcareServiceGoogleChrome", "/form[@title~'^CURA\\ Healthcare\\ Service\\ -']", parentFolder, 30000, null, true, "84e8fc4d-1d0e-4511-87b0-68090e09674d", "")
            {
                _element241933216Info = new RepoItemInfo(this, "Element241933216", "element[@controlid='241933216']", 30000, null, "2a502828-eb78-4995-bbfa-4e1d1cfbe7b4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84e8fc4d-1d0e-4511-87b0-68090e09674d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84e8fc4d-1d0e-4511-87b0-68090e09674d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element241933216 item.
            /// </summary>
            [RepositoryItem("2a502828-eb78-4995-bbfa-4e1d1cfbe7b4")]
            public virtual Ranorex.Unknown Element241933216
            {
                get
                {
                    return _element241933216Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element241933216 item info.
            /// </summary>
            [RepositoryItemInfo("2a502828-eb78-4995-bbfa-4e1d1cfbe7b4")]
            public virtual RepoItemInfo Element241933216Info
            {
                get
                {
                    return _element241933216Info;
                }
            }
        }

    }
#pragma warning restore 0436
}