///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CURARanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("500789da-8747-4caa-abc7-f78b68f3c582", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CURARanorexRepository repository.
        /// </summary>
        public static CURARanorexRepository repo = CURARanorexRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://demoaut.katalon.com/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://demoaut.katalon.com/", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 886;29.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(1));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("886;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 707;115.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(2));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("707;115");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 527;194.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(3));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("527;194");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{Ckey}{LControlKey up}' with focus on 'CURAHealthcareServiceGoogleChrome'.", repo.CURAHealthcareServiceGoogleChrome.SelfInfo, new RecordItemIndex(4));
            repo.CURAHealthcareServiceGoogleChrome.Self.PressKeys("{LControlKey down}{Akey}{Ckey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 481;326.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(5));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("481;326");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+V' Press with focus on 'CURAHealthcareServiceGoogleChrome'.", repo.CURAHealthcareServiceGoogleChrome.SelfInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.CURAHealthcareServiceGoogleChrome.Self);
            Keyboard.Press(System.Windows.Forms.Keys.V | System.Windows.Forms.Keys.Control, 47, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 504;259.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(7));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("504;259");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{Ckey}{LControlKey up}' with focus on 'CURAHealthcareServiceGoogleChrome'.", repo.CURAHealthcareServiceGoogleChrome.SelfInfo, new RecordItemIndex(8));
            repo.CURAHealthcareServiceGoogleChrome.Self.PressKeys("{LControlKey down}{Akey}{Ckey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 465;370.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(9));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("465;370");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+V' Press with focus on 'CURAHealthcareServiceGoogleChrome'.", repo.CURAHealthcareServiceGoogleChrome.SelfInfo, new RecordItemIndex(10));
            Keyboard.PrepareFocus(repo.CURAHealthcareServiceGoogleChrome.Self);
            Keyboard.Press(System.Windows.Forms.Keys.V | System.Windows.Forms.Keys.Control, 47, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CURAHealthcareServiceGoogleChrome.Element241933216' at 449;422.", repo.CURAHealthcareServiceGoogleChrome.Element241933216Info, new RecordItemIndex(11));
            repo.CURAHealthcareServiceGoogleChrome.Element241933216.Click("449;422");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
